Algoritmo "matriz3x2"

Var
v: vetor[1..3,1..2] de inteiro
l,c: inteiro

Inicio
      para l <- 1 ate 3 faca
           para c <- 1 ate 2 faca
                escreva("Infome o valor da posição [", l,",", c,"]: ")
                leia(v[l,c])
           fimpara
      fimpara
      para l <- 1 ate 3 faca
           para c <- 1 ate 2 faca
                escreva(v[l,c])
           fimpara
           escreval()
      fimpara



Fimalgoritmo