Algoritmo "somaparametrosreferencia"

Var
x,y: inteiro

procedimento soma(var a, b: inteiro)
inicio
      a <- a+1
      b <- b+2
      escreval("Valor de A = ", a)
      escreval("Valor de B = ", b)
      escreval("Soma de A + B = ", a+b)
fimprocedimento

Inicio
      x <- 4
      y <- 8
      soma(x, y)
      Escreval("O valor de X = ", x)
      Escreval("O valor de Y = ", y)


Fimalgoritmo